// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipnbwzshkgljzuvvoesz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbmJ3enNoa2dsanp1dnZvZXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTY4MjAsImV4cCI6MjA1OTc5MjgyMH0.Lzuo3qqXinedI8WcYFthPdJpFB-U1UjfFqbJe0TbgpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);